
module.exports = {
  production: {
    deployPath: 'C:\\inetpub\\wwwroot\\spectrak',
    debug: false,
    express: {
      port: process.env.PORT || 3000,
      host: process.env.WEBSITE_HOSTNAME || `localhost:${process.env.PORT || 3000}`,
      siteRoot: '/spectrak/'
    },
    sequelize: {
      host: 'DISENGSQLPR1',
      database: 'FIS_CONED',
      username: 'netstorm_ro',
      password: 'netstorm_ro',
      schema: 'spectrak',
      logging: false,
      forceSync: false
    }
  },
  development: {
    deployPath: 'C:\\inetpub\\wwwroot\\spectrak',
    debug: true,
    express: {
      port: process.env.PORT || 3000,
      host: process.env.WEBSITE_HOSTNAME || `localhost:${process.env.PORT || 3000}`,
      siteRoot: '/spectrak/'
    },
    sequelize: {
      host: 'SQLDEN12R4E01',
      database: 'FIS_CONED',
      username: 'netstorm_ro',
      password: 'netstorm_ro',
      schema: 'spectrak',
      logging: true,
      forceSync: true,
      initialData: {
        specifications: [
          { type: 'EO', documentNumber: '10359', title: '', issueDate: new Date(), sectionCode: '123', subSectionCode: '123', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: false },
          { type: 'EO', documentNumber: '10359', title: 'UPDATED', issueDate: new Date(), sectionCode: '123', subSectionCOde: '123', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '2643', title: 'DION IS BLEH', issueDate:'2010-01-27', sectionCode: '690', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '5027', title: 'DION IS BLEH', issueDate:'2013-10-27', sectionCode: '361', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '8837', title: 'DION SMELLS BAD', issueDate:'2015-02-12', sectionCode: '487', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '9102', title: 'DION IS QUITE ROTUND', issueDate:'2012-12-28', sectionCode: '937', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '2339', title: 'DION IS BLEH', issueDate:'2013-07-01', sectionCode: '260', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '8993', title: 'DION SMELLS BAD', issueDate:'2014-03-19', sectionCode: '612', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '8231', title: 'DION SMELLS BAD', issueDate:'2012-11-02', sectionCode: '811', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '3561', title: 'DION IS BLEH', issueDate:'2012-01-05', sectionCode: '176', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '6316', title: 'DION IS BLEH', issueDate:'2015-12-26', sectionCode: '896', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '4539', title: 'DION SMELLS BAD', issueDate:'2014-11-10', sectionCode: '881', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '4618', title: 'DION SMELLS BAD', issueDate:'2015-07-02', sectionCode: '700', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '9482', title: 'DION SMELLS BAD', issueDate:'2013-12-06', sectionCode: '525', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '5194', title: 'DION IS QUITE ROTUND', issueDate:'2014-07-20', sectionCode: '278', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '7001', title: 'DION IS BLEH', issueDate:'2010-02-28', sectionCode: '284', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '6135', title: 'DION IS QUITE ROTUND', issueDate:'2010-03-29', sectionCode: '232', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '8629', title: 'DION IS QUITE ROTUND', issueDate:'2012-08-01', sectionCode: '238', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '2693', title: 'DION SMELLS BAD', issueDate:'2014-11-29', sectionCode: '548', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '8421', title: 'DION SMELLS BAD', issueDate:'2014-06-16', sectionCode: '934', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '3823', title: 'DION IS QUITE ROTUND', issueDate:'2014-04-24', sectionCode: '404', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '3738', title: 'DION SMELLS BAD', issueDate:'2012-10-25', sectionCode: '326', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '6447', title: 'DION IS BLEH', issueDate:'2014-09-16', sectionCode: '321', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '1490', title: 'DION IS BLEH', issueDate:'2014-01-03', sectionCode: '216', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '3722', title: 'DION IS BLEH', issueDate:'2010-03-03', sectionCode: '489', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '6490', title: 'DION SMELLS BAD', issueDate:'2012-01-19', sectionCode: '109', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '7395', title: 'DION IS QUITE ROTUND', issueDate:'2010-01-03', sectionCode: '599', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '8362', title: 'DION IS BLEH', issueDate:'2010-10-28', sectionCode: '202', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '2233', title: 'DION IS QUITE ROTUND', issueDate:'2013-09-25', sectionCode: '195', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '5297', title: 'DION IS QUITE ROTUND', issueDate:'2010-07-09', sectionCode: '534', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '9663', title: 'DION IS QUITE ROTUND', issueDate:'2014-07-10', sectionCode: '724', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '8161', title: 'DION SMELLS BAD', issueDate:'2013-09-23', sectionCode: '179', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '8825', title: 'DION IS BLEH', issueDate:'2014-07-01', sectionCode: '543', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '3158', title: 'DION IS QUITE ROTUND', issueDate:'2014-02-01', sectionCode: '261', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '9990', title: 'DION IS QUITE ROTUND', issueDate:'2013-12-07', sectionCode: '560', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '1128', title: 'DION IS BLEH', issueDate:'2011-11-22', sectionCode: '412', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '2535', title: 'DION IS BLEH', issueDate:'2015-04-11', sectionCode: '138', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '5047', title: 'DION IS QUITE ROTUND', issueDate:'2016-05-07', sectionCode: '485', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '1265', title: 'DION SMELLS BAD', issueDate:'2015-07-15', sectionCode: '325', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '7652', title: 'DION IS BLEH', issueDate:'2012-12-04', sectionCode: '998', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '1277', title: 'DION SMELLS BAD', issueDate:'2014-05-02', sectionCode: '279', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '9173', title: 'DION IS BLEH', issueDate:'2012-07-03', sectionCode: '288', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '3990', title: 'DION IS BLEH', issueDate:'2010-11-12', sectionCode: '926', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '8128', title: 'DION SMELLS BAD', issueDate:'2015-02-10', sectionCode: '241', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '4922', title: 'DION IS QUITE ROTUND', issueDate:'2011-10-31', sectionCode: '369', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '2787', title: 'DION SMELLS BAD', issueDate:'2015-10-05', sectionCode: '489', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EOP', documentNumber: '8630', title: 'DION IS BLEH', issueDate:'2014-08-05', sectionCode: '689', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '6403', title: 'DION IS QUITE ROTUND', issueDate:'2015-04-15', sectionCode: '564', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '6955', title: 'DION SMELLS BAD', issueDate:'2016-12-17', sectionCode: '979', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '6646', title: 'DION IS BLEH', issueDate:'2016-09-24', sectionCode: '963', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'B', documentNumber: '1936', title: 'DION IS QUITE ROTUND', issueDate:'2011-12-01', sectionCode: '578', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true },
          { type: 'EO', documentNumber: '1933', title: 'DION IS QUITE ROTUND', issueDate:'2011-01-16', sectionCode: '627', isDwg: false, createdBy: 'CONED\\AHMEATJD', isActive: true }

        ],
        associatedRegulations: [
          { citationNumber: 'B991-338', name: 'White', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:13 },
          { citationNumber: 'B991-338', name: 'White', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:38 },
          { citationNumber: 'BD822-2C', name: 'Red', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:13 },
          { citationNumber: '04-D-2837', name: 'Blue', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:49 },
          { citationNumber: 'BD822-2C', name: 'White', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:18 },
          { citationNumber: '9948-M-288', name: 'Blue', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:38 },
          { citationNumber: '04-D-2837', name: 'Red', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:41 },
          { citationNumber: 'B991-338', name: 'Blue', regulatedBy: 'PSC', description: 'Lorem ipsum..', specificationId:15 },
          { citationNumber: 'B991-338', name: 'White', regulatedBy: 'PSC', description: 'Lorem ipsum..', specificationId:14 },
          { citationNumber: 'B991-338', name: 'Red', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:7 },
          { citationNumber: '9948-M-288', name: 'Blue', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:25 },
          { citationNumber: '9948-M-288', name: 'Red', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:21 },
          { citationNumber: 'BD822-2C', name: 'Red', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:10 },
          { citationNumber: '04-D-2837', name: 'Blue', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:43 },
          { citationNumber: '04-D-2837', name: 'Red', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:17 },
          { citationNumber: 'B991-338', name: 'Red', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:39 },
          { citationNumber: '9948-M-288', name: 'Red', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:24 },
          { citationNumber: '04-D-2837', name: 'White', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:27 },
          { citationNumber: '04-D-2837', name: 'Red', regulatedBy: 'PSC', description: 'Lorem ipsum..', specificationId:22 },
          { citationNumber: '04-D-2837', name: 'Blue', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:9 },
          { citationNumber: 'B991-338', name: 'Blue', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:12 },
          { citationNumber: '04-D-2837', name: 'Blue', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:12 },
          { citationNumber: '9948-M-288', name: 'Red', regulatedBy: 'PSC', description: 'Lorem ipsum..', specificationId:20 },
          { citationNumber: 'BD822-2C', name: 'Blue', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:29 },
          { citationNumber: '9948-M-288', name: 'Red', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:33 },
          { citationNumber: '04-D-2837', name: 'Red', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:32 },
          { citationNumber: 'B991-338', name: 'Red', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:1 },
          { citationNumber: 'B991-338', name: 'Blue', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:39 },
          { citationNumber: '9948-M-288', name: 'Blue', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:15 },
          { citationNumber: '04-D-2837', name: 'White', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:16 },
          { citationNumber: 'BD822-2C', name: 'White', regulatedBy: 'PSC', description: 'Lorem ipsum..', specificationId:46 },
          { citationNumber: '04-D-2837', name: 'Blue', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:50 },
          { citationNumber: 'B991-338', name: 'Blue', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:21 },
          { citationNumber: 'B991-338', name: 'Red', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:2 },
          { citationNumber: 'BD822-2C', name: 'Blue', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:29 },
          { citationNumber: 'BD822-2C', name: 'Blue', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:2 },
          { citationNumber: '9948-M-288', name: 'Blue', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:42 },
          { citationNumber: 'B991-338', name: 'Red', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:50 },
          { citationNumber: 'BD822-2C', name: 'White', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:41 },
          { citationNumber: '04-D-2837', name: 'Red', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:27 },
          { citationNumber: 'B991-338', name: 'Red', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:9 },
          { citationNumber: 'B991-338', name: 'Blue', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:46 },
          { citationNumber: 'B991-338', name: 'Blue', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:50 },
          { citationNumber: '9948-M-288', name: 'White', regulatedBy: 'PSC', description: 'Amet hane..', specificationId:19 },
          { citationNumber: 'BD822-2C', name: 'White', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:1 },
          { citationNumber: 'BD822-2C', name: 'White', regulatedBy: 'NESC', description: 'Lorem ipsum..', specificationId:35 },
          { citationNumber: '04-D-2837', name: 'Blue', regulatedBy: 'NESC', description: 'Amet hane..', specificationId:38 },
          { citationNumber: '9948-M-288', name: 'White', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:5 },
          { citationNumber: '9948-M-288', name: 'White', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:48 },
          { citationNumber: 'BD822-2C', name: 'Blue', regulatedBy: 'PSC', description: 'Dolor sit ...', specificationId:34 },
          { citationNumber: 'B991-338', name: 'Blue', regulatedBy: 'NESC', description: 'Dolor sit ...', specificationId:34 }
        ],
        associatedRegulationParts: [
          { section:'7719', description: 'regulation part desc', associatedRegulationId: 49},
          { section:'4030', description: 'regulation part desc', associatedRegulationId: 35},
          { section:'6387', description: 'regulation part desc', associatedRegulationId: 44},
          { section:'4751', description: 'regulation part desc', associatedRegulationId: 21},
          { section:'8226', description: 'regulation part desc', associatedRegulationId: 38},
          { section:'9943', description: 'regulation part desc', associatedRegulationId: 22},
          { section:'7500', description: 'regulation part desc', associatedRegulationId: 46},
          { section:'7683', description: 'regulation part desc', associatedRegulationId: 43},
          { section:'5701', description: 'regulation part desc', associatedRegulationId: 21},
          { section:'3221', description: 'regulation part desc', associatedRegulationId: 34},
          { section:'4562', description: 'regulation part desc', associatedRegulationId: 23},
          { section:'9057', description: 'regulation part desc', associatedRegulationId: 41},
          { section:'6362', description: 'regulation part desc', associatedRegulationId: 21},
          { section:'1043', description: 'regulation part desc', associatedRegulationId: 50},
          { section:'9463', description: 'regulation part desc', associatedRegulationId: 11},
          { section:'721', description: 'regulation part desc', associatedRegulationId: 31},
          { section:'2584', description: 'regulation part desc', associatedRegulationId: 46},
          { section:'6196', description: 'regulation part desc', associatedRegulationId: 28},
          { section:'4822', description: 'regulation part desc', associatedRegulationId: 21},
          { section:'165', description: 'regulation part desc', associatedRegulationId: 46},
          { section:'1996', description: 'regulation part desc', associatedRegulationId: 1},
          { section:'5802', description: 'regulation part desc', associatedRegulationId: 34},
          { section:'2009', description: 'regulation part desc', associatedRegulationId: 23},
          { section:'3983', description: 'regulation part desc', associatedRegulationId: 7},
          { section:'1261', description: 'regulation part desc', associatedRegulationId: 17},
          { section:'7802', description: 'regulation part desc', associatedRegulationId: 44},
          { section:'9694', description: 'regulation part desc', associatedRegulationId: 13},
          { section:'7147', description: 'regulation part desc', associatedRegulationId: 15},
          { section:'9125', description: 'regulation part desc', associatedRegulationId: 37},
          { section:'5076', description: 'regulation part desc', associatedRegulationId: 19},
          { section:'6048', description: 'regulation part desc', associatedRegulationId: 45},
          { section:'2796', description: 'regulation part desc', associatedRegulationId: 3},
          { section:'6590', description: 'regulation part desc', associatedRegulationId: 8},
          { section:'1696', description: 'regulation part desc', associatedRegulationId: 14},
          { section:'5947', description: 'regulation part desc', associatedRegulationId: 4},
          { section:'6553', description: 'regulation part desc', associatedRegulationId: 29},
          { section:'6661', description: 'regulation part desc', associatedRegulationId: 12},
          { section:'3413', description: 'regulation part desc', associatedRegulationId: 19},
          { section:'2101', description: 'regulation part desc', associatedRegulationId: 12},
          { section:'3151', description: 'regulation part desc', associatedRegulationId: 17},
          { section:'7330', description: 'regulation part desc', associatedRegulationId: 16},
          { section:'314', description: 'regulation part desc', associatedRegulationId: 20},
          { section:'4605', description: 'regulation part desc', associatedRegulationId: 48},
          { section:'3726', description: 'regulation part desc', associatedRegulationId: 45},
          { section:'4109', description: 'regulation part desc', associatedRegulationId: 48},
          { section:'3982', description: 'regulation part desc', associatedRegulationId: 30},
          { section:'2135', description: 'regulation part desc', associatedRegulationId: 50},
          { section:'8948', description: 'regulation part desc', associatedRegulationId: 24},
          { section:'2591', description: 'regulation part desc', associatedRegulationId: 34},
          { section:'9603', description: 'regulation part desc', associatedRegulationId: 13},
          { section:'2154', description: 'regulation part desc', associatedRegulationId: 45}          
        ],
        specificationAssociations: [
          { specificationId: 4, associatedSpecificationId: 34},
          { specificationId: 47, associatedSpecificationId: 35},
          { specificationId: 26, associatedSpecificationId: 5},
          { specificationId: 44, associatedSpecificationId: 38},
          { specificationId: 1, associatedSpecificationId: 6},
          { specificationId: 39, associatedSpecificationId: 8},
          { specificationId: 37, associatedSpecificationId: 42},
          { specificationId: 31, associatedSpecificationId: 50},
          { specificationId: 29, associatedSpecificationId: 17},
          { specificationId: 16, associatedSpecificationId: 19},
          { specificationId: 21, associatedSpecificationId: 43},
          { specificationId: 5, associatedSpecificationId: 31},
          { specificationId: 24, associatedSpecificationId: 30},
          { specificationId: 46, associatedSpecificationId: 13},
          { specificationId: 19, associatedSpecificationId: 18},
          { specificationId: 31, associatedSpecificationId: 47},
          { specificationId: 20, associatedSpecificationId: 34},
          { specificationId: 40, associatedSpecificationId: 20},
          { specificationId: 16, associatedSpecificationId: 9},
          { specificationId: 33, associatedSpecificationId: 45},
          { specificationId: 20, associatedSpecificationId: 14},
          { specificationId: 39, associatedSpecificationId: 25},
          { specificationId: 48, associatedSpecificationId: 10},
          { specificationId: 5, associatedSpecificationId: 2},
          { specificationId: 29, associatedSpecificationId: 18},
          { specificationId: 12, associatedSpecificationId: 21},
          { specificationId: 23, associatedSpecificationId: 4},
          { specificationId: 27, associatedSpecificationId: 7},
          { specificationId: 40, associatedSpecificationId: 40},
          { specificationId: 26, associatedSpecificationId: 25},
          { specificationId: 29, associatedSpecificationId: 45},
          { specificationId: 7, associatedSpecificationId: 4},
          { specificationId: 37, associatedSpecificationId: 29},
          { specificationId: 26, associatedSpecificationId: 19},
          { specificationId: 28, associatedSpecificationId: 50},
          { specificationId: 19, associatedSpecificationId: 7},
          { specificationId: 32, associatedSpecificationId: 50},
          { specificationId: 30, associatedSpecificationId: 24},
          { specificationId: 15, associatedSpecificationId: 31},
          { specificationId: 44, associatedSpecificationId: 18},
          { specificationId: 41, associatedSpecificationId: 22},
          { specificationId: 39, associatedSpecificationId: 37},
          { specificationId: 42, associatedSpecificationId: 19},
          { specificationId: 6, associatedSpecificationId: 20},
          { specificationId: 36, associatedSpecificationId: 14},
          { specificationId: 13, associatedSpecificationId: 10},
          { specificationId: 14, associatedSpecificationId: 23},
          { specificationId: 36, associatedSpecificationId: 26},
          { specificationId: 17, associatedSpecificationId: 1},
          { specificationId: 37, associatedSpecificationId: 21}
        ]
      }
    }
  }
};
